package project.models;

public enum Category {
	AMERICAN, ASIAN, BREAKFAST, BURGERS, CHEESE, CHINESE, COFFEE, DRINKS, HALAL, ICECREAM, INDIAN, JAPANESE, KOREAN, PIZZA, SALADS, SANDWICHES, SUSHI, VEGETARIAN, TACOS, VIETNAMESE
}
